### ISSUE TITLE
How do batch size come into play in the S3IM formulation

### ISSUE THREAD

**Issue by haiphamcse** [Madaoer/S3IM-Neural-Fields#1]
Hi there, loved your work and currently trying to add it to some neural field research. I have a question about the batch size of a ray in your formulation:
1/ Suppose a batched ray size (batch, num_rays, 3). How would we construct a patch P? I'm currently iterating through each batch (num_rays, 3) batch times and averaging the results. However I noticed here that the loss varies with different batch size (more batch -> higher losses). Is this consistent with your formulation?
2/ Have you tested with other patch size other than 64x64. Does bigger patch size have any affects on perfomance?

**Comment by Madaoer** [comment]
Hello haiphamcse
1. We use the final rgb piexl(batch, 3) instead of intermediate rgb points(batch, num_rays, 3) to make a virtual patch. For example, (4096, 3) --> (64, 64, 3). 
2. We use 64 x 64 because in original nerf methods(DVGO, TensoRF) use 4096 as default setting. Due to the repeat time in our methods, I think s3im already have enough randomness, so a bigger patch size maybe not that helpful.

**Comment by haiphamcse** [comment]
What is the right way to use S3IM if the number of rgb pixels is larger than (4096,3). Do we just change the kernel size proportionally?

**Comment by Madaoer** [comment]
No need for increasing kernel size. For example, we can keep the virtual patch as a shape like (64, batch_size / 64 / 3, 3)

**Comment by haiphamcse** [comment]
Thank you for your reply! I understand now

**Comment by piwawa** [comment]
> No need for increasing kernel size. For example, we can keep the virtual patch as a shape like (64, batch_size / 64 / 3, 3)

**(64, batch_size / 64 / 3, 3)** 

What is this meaning? I have (256^2, 3) rays as `src_vec, tar_vec` variables, how to set the following parameters?

`def __init__(self, kernel_size=4, stride=4, repeat_time=10, patch_height=64, patch_width=64):`

**Comment by Madaoer** [comment]
> > No need for increasing kernel size. For example, we can keep the virtual patch as a shape like (64, batch_size / 64 / 3, 3)
> 
> **(64, batch_size / 64 / 3, 3)**
> 
> What is this meaning? I have (256^2, 3) rays as `src_vec, tar_vec` variables, how to set the following parameters?
> 
> `def __init__(self, kernel_size=4, stride=4, repeat_time=10, patch_height=64, patch_width=64):`

I think you can set patch_width to 256^2/64.

**Comment by piwawa** [comment]
> > > No need for increasing kernel size. For example, we can keep the virtual patch as a shape like (64, batch_size / 64 / 3, 3)
> > 
> > 
> > **(64, batch_size / 64 / 3, 3)**
> > What is this meaning? I have (256^2, 3) rays as `src_vec, tar_vec` variables, how to set the following parameters?
> > `def __init__(self, kernel_size=4, stride=4, repeat_time=10, patch_height=64, patch_width=64):`
> 
> I think you can set patch_width to 256^2/64.

Thank you, I got it!
