### ISSUE TITLE
How to make sure s3im input matching the patch size

### ISSUE THREAD

**Issue by nemorix** [Madaoer/S3IM-Neural-Fields#10]
How to make sure s3im input matching the patch size? If the best patch size is 64, Is it necessary to modify the shape of my input?
Thank you for your answer.

s3im_func(src,tar)

tar_patch = tar_all.permute(1, 0).reshape(1, 3, self.patch_height, self.patch_width * self.repeat_time)
src_patch = src_all.permute(1, 0).reshape(1, 3, self.patch_height, self.patch_width * self.repeat_time)

**Comment by Madaoer** [comment]
@nemorix I don't think the shape of virtual patch will affect the performance so much. You can choose a rectangular one or a square one as you like.

**Comment by nemorix** [comment]
Ok, thanks for this answer, it is very helpful!
