### ISSUE TITLE
How can I obtain data?if I use my images how can I configure them?

### ISSUE THREAD

**Issue by SynRovo** [Madaoer/S3IM-Neural-Fields#11]
"Could you please explain what 'office0.ply,' '000000_depth.npy,' '000000_depth.png,' '000000_mask.npy,' '000000_normal.npy,' '000000_normal.png,' and '000000_rgb.png' in the dataset within the 'data' directory are? How can I obtain them?"

**Comment by Madaoer** [comment]
Sorry for the late reply.
I think these files are from Replica dataset. You can donwload [Replica](https://s3.eu-central-1.amazonaws.com/avg-projects/monosdf/data/Replica.tar) dataset here.
