### ISSUE TITLE
Unable to converge

### ISSUE THREAD

**Issue by xuyaojian123** [Madaoer/S3IM-Neural-Fields#12]
i want to add s3im loss in k-planes, but it unable to converge. This is because k-planes adds random background during the training process？
![image](https://github.com/Madaoer/S3IM-Neural-Fields/assets/51220835/69c7151b-bd82-43a6-ac1c-d9df446476a0)

**Comment by Madaoer** [comment]
Sorry for the late reply.
I think you can try a smaller s3im loss weight.
