### ISSUE TITLE
Question about applying S3IM to NeRFs which using ramdom sampling

### ISSUE THREAD

**Issue by imabackstabber** [Madaoer/S3IM-Neural-Fields#14]
Hi. I've been reading your paper 'S3IM: Stochastic Structural SIMilarity and Its Unreasonable Effectiveness for Neural Fields'. It's a great work! However, I have some questions about S3IM.

I noticed that in table 10, where scene setting to `Truck` and model setting to `DVGO`. I found that during training DVGO, the rays used for training is somehow generated by random permutation:

```
def batch_indices_generator(N, BS):
 # torch.randperm on cuda produce incorrect results in my machine
 idx, top = torch.LongTensor(np.random.permutation(N)), 0
 while True:
  if top + BS > N:
   idx, top = torch.LongTensor(np.random.permutation(N)), 0
  yield idx[top:top+BS]
  top += BS 
...
index_generator = dvgo.batch_indices_generator(len(rgb_tr), cfg_train.N_rand)
batch_index_sampler = lambda: next(index_generator)
...
# random sample rays
if cfg_train.ray_sampler in ['flatten', 'in_maskcache']:
 sel_i = batch_index_sampler()
 target = rgb_tr[sel_i]
 rays_o = rays_o_tr[sel_i]
 rays_d = rays_d_tr[sel_i]
 viewdirs = viewdirs_tr[sel_i]

```

This is fine when applying S3IM loss on them since S3IM will randomly permute them again. But I wonder how did you apply SSIM loss on it. Since the rays sampled are randomly generated, how does SSIM loss penalize them? If it just penalizes those rays without any processing, won't it make SSIM behave just like S3IM(since rendered pixels are shuffled)?

I try my best but can't figure out how it works. I hope you can shed some light on me, that will be very helpful!

**Comment by Madaoer** [comment]
Sorry for the late reply.
If we want to actually leverage SSIM in DVGO, then we should write a new data sample code to load local patches from training images instead of random rays.

**Comment by imabackstabber** [comment]
ok, I got it. Thanks.
