### ISSUE TITLE
Issue when trying to run DVGO train_replica

### ISSUE THREAD

**Issue by jpsml** [Madaoer/S3IM-Neural-Fields#2]
There is a typo in the name of the "scripts" folder, its name is "scrips" instead of "scripts".

Also, in "models/DVGO/run.py", I needed to add the following line before the line with `from model_components import S3IM`:

`sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))`

**Comment by jpsml** [comment]
In order to run DVGO with custom Otobai data, I also needed to modify "models/DVGO/configs/custom/Otobai.py" as follows:

```
fine_train = dict(
    N_iters=30000,
    N_rand=4096,
    weight_distortion=0.01,
    pg_scale=[2000,4000,6000,8000],
    decay_after_scale=0.1,
    ray_sampler='flatten',
    tv_before=1e9,
    tv_dense_before=10000,
    weight_tv_density=1e-5,
    weight_tv_k0=1e-6,
    s3im_weight=1.0,
    s3im_kernel=4,
    s3im_stride=4,
    s3im_repeat_time=10,
    s3im_patch_height=64,
    s3im_patch_width=64,
)
```

But I am getting out of memory on my RTX 3090.

**Comment by Madaoer** [comment]
Sorry for the late reply. Thanks for your suggestions in typo, I will update soon.
1. I think it works well in linux, what's your operate system?
2.  You can try to comment the line https://github.com/Madaoer/S3IM-Neural-Fields/blob/main/models/DVGO/run.py#404. I add this line for speeding up training, but it may cause the out of memory error in cuda.

**Comment by jpsml** [comment]
1. It's Ubuntu 20.04
2. After commenting the line, I was able to run, but got bad results: https://drive.google.com/file/d/1HnbPhD3-H94dRRwrc2LcnKSvukfm5aYD/view?usp=sharing
Do you have any clue of what may be causing this issue?

**Comment by jpsml** [comment]
Solved it, it was an issue with COLMAP.
