### ISSUE TITLE
About the virtual patch

### ISSUE THREAD

**Issue by 1999kevin** [Madaoer/S3IM-Neural-Fields#3]
Simple but very nice job! 

I'm not sure about the definition of virtual patch. Do you mean it is not a real patch because you just random select rays from the dataloader and compose a square patch with reshape method? I'm doubt for the structural constrain provided by this random virtual patch because it actually do not provide accurate structural information. 

BTW, could you please comment the dimension and shape of the _src_vec_ and _tar_vec_, who are the input of S3IM forward function?

**Comment by yangwill81** [comment]
Great job~~ I'm also interested in this issue. Can this loss be used in other tasks such as segmentation?

**Comment by Madaoer** [comment]
Sorry for the late reply.

@1999kevin 
1. Yes, that is how virtual patch works.
2. We believe that S3IM could extract the global structural information which is different from local structural information.
3. Thanks for your suggestion, the default shape of *src_vec* is [B, 3]. BTW, in S3IM, both *src_vec* and *tar_vec* are the input of S3IM.

@yangwill81 
I think it might work as well, you can try it.
