### ISSUE TITLE
About the use of S3IM.

### ISSUE THREAD

**Issue by islandLZ** [Madaoer/S3IM-Neural-Fields#4]
If I want to directly calculate the S3IM value between two images (3 * 512 * 512), how should I use the S3IM class?
![image](https://github.com/Madaoer/S3IM-Neural-Fields/assets/65443889/f6757c62-20a0-485e-81a8-774c2c1ec714)

**Comment by Madaoer** [comment]
Sorry for the late reply.
I think you can flatten the image into a vector and then use the S3IM.
