### ISSUE TITLE
Understanding of the upper s3im

### ISSUE THREAD

**Issue by mowangmodi** [Madaoer/S3IM-Neural-Fields#5]
hi，The shape of rgb (srcvec) I entered is (1024,3), and the shape of gt (tar_vec) is also (1024,3). I used the parameter M=10 (repeat_time=10), patch_ Height=32, patch_ Width=32. My understanding is to transform the rgb predicted by my network into an image and gt into an image. After 10 for loops, each loop is in a random order, and the shape of both images is (1, 3, 32，320). Then, calculate s3im based on these two images? Is my understanding correct?

**Comment by Madaoer** [comment]
> hi，The shape of rgb (srcvec) I entered is (1024,3), and the shape of gt (tar_vec) is also (1024,3). I used the parameter M=10 (repeat_time=10), patch_ Height=32, patch_ Width=32. My understanding is to transform the rgb predicted by my network into an image and gt into an image. After 10 for loops, each loop is in a random order, and the shape of both images is (1, 3, 32，320). Then, calculate s3im based on these two images? Is my understanding correct?

Yes, that is how S3IM works.
