### ISSUE TITLE
 How should I set the weights？？

### ISSUE THREAD

**Issue by Shichao123123** [Madaoer/S3IM-Neural-Fields#7]
very nice work! but i do not know how to set the weight?
![image](https://github.com/Madaoer/S3IM-Neural-Fields/assets/133303907/e0145f74-f1a0-477e-82f8-9218a40f6402)
whether this should be like this  
![image](https://github.com/Madaoer/S3IM-Neural-Fields/assets/133303907/4b3a295f-6a31-4dc0-a9bb-6f623e902cff)

**Comment by Madaoer** [comment]
Yes, you can select the weight of s3im in this range. In addition, you can finetune the weight to get the best performance.

**Comment by Madaoer** [comment]
@Shichao123123 In addition, you can set the s3im weight by changing the config file.
```
#for TensoRF
models/TensoRF/configs/replica_exp/replica_scan1_s3im_1.0.txt
#for DVGO
models/DVGO/configs/replica_exp/replica_scan1_s3im_1.0.txt
```

**Comment by Shichao123123** [comment]
> @Shichao123123 In addition, you can set the s3im weight by changing the config file.
> 
> ```
> #for TensoRF
> models/TensoRF/configs/replica_exp/replica_scan1_s3im_1.0.txt
> #for DVGO
> models/DVGO/configs/replica_exp/replica_scan1_s3im_1.0.txt
> ```
 Got it！thank you very much for your reply
