### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by AoxiangFan** [Madaoer/S3IM-Neural-Fields#8]
Hi thanks for sharing the great work!

I tried the code on Replica dataset (with TensoRF model), on scan1 to 7 it gives close PSNR values to the reported results, but for scan 8, I got 24.42 PSNR which is far from the reported 39.59 in the paper.

Is it normal? Does it also happen on your machine?

Thanks in advance!

**Comment by Madaoer** [comment]
> Hi thanks for sharing the great work!
> 
> I tried the code on Replica dataset (with TensoRF model), on scan1 to 7 it gives close PSNR values to the reported results, but for scan 8, I got 24.42 PSNR which is far from the reported 39.59 in the paper.
> 
> Is it normal? Does it also happen on your machine?
> 
> Thanks in advance!

Sorry for the late reply. Try setting s3im_weight=5 in Replica scan8.

**Comment by AoxiangFan** [comment]
Thanks for your reply! I am also wondering if you can also share the TanksAndTemples dataset used in the paper? I tried to find it but it seems that your dataset is pre-processed. Thanks a lot!

**Comment by Madaoer** [comment]
@AoxiangFan sry for the late reply. You can modify the TanksAndTemples dataset according to the description in our paper. I will share the dataset lately.

**Comment by ZachL1** [comment]
@Madaoer  Hello! Are you still planning to share the TanksAndTemples dataset? Thank you very much for your contribution to the open-source community!
